#!/bin/bash
# App-Comprador Quick Commands

echo "🚀 App-Comprador Commands"
echo "========================"
echo ""
echo "1. Instalar dependencias:"
echo "   npm install"
echo ""
echo "2. Iniciar dev server:"
echo "   npm start"
echo ""
echo "3. Ejecutar en Android (emulador/dispositivo):"
echo "   npm run android"
echo ""
echo "4. Ejecutar en iOS:"
echo "   npm run ios"
echo ""
echo "5. Ejecutar en web:"
echo "   npm run web"
echo ""
echo "6. Verificar tipos TypeScript:"
echo "   npx tsc --noEmit"
echo ""
echo "7. Limpiar caché y reinstalar:"
echo "   rm -rf node_modules package-lock.json && npm install"
echo ""
echo "📱 Características:"
echo "   ✅ Home: resumen y control de gastos"
echo "   ✅ Comprar: lista con advertencia de sobreprecio"
echo "   ✅ Base de datos: CRUD de productos"
echo "   ✅ Informe: historial de compras"
echo "   ✅ Cervezas: recurrentes (holanda, brahma, imperial)"
echo "   ✅ Snackbars: feedback tras acciones"
echo ""
